name: LongLaoshi
description: Proyecto para el curso de Ingenieria de Requisitos
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  flutter_riverpod: ^2.4.9
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  intl: ^0.18.0
  dash_chat_2: ^0.0.18
  chat_gpt_sdk: ^2.2.8
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: Mukta
      fonts: 
        - asset: assets/fonts/MuktaSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MuktaMedium.ttf
          weight: 500
    - family: Josefin Sans
      fonts: 
        - asset: assets/fonts/JosefinSansRomanMedium.ttf
          weight: 500
